language: python

cache: pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

python:
  - "3.7"

before_install:
  - pip install -U pip
  - npm install -g npm

install: "pip install -U -r requirements/dev.txt"

script: pytest --ignore=node_modules
