db:
  image: postgres
  environment:
    - POSTGRES_USER=jing
    - POSTGRES_PASSWORD=123456

redis:
  image: redis

nginx:
  image: nginx
  links:
    - sun_app:uwsgi
  ports:
     - "80:80"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./static/.:/var/web/static
    - ./media/.:/var/web/media

sun_app:
  build: .
  environment:
    - PORT=8000
    - STATIC=/app/static

  volumes:
    - .:/app

  expose:
    - "8000"

  links:
    - redis:redis
    - db:postgres
